# Generated by Django 4.1.7 on 2023-03-03 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('surname', models.CharField(max_length=50, verbose_name='Surname')),
                ('position', models.CharField(choices=[('director', 'Director'), ('associate director', 'Associate Director'), ('secretary', 'Secretary')], max_length=150)),
                ('address', models.CharField(max_length=50, verbose_name='Address')),
                ('phone', models.CharField(max_length=11)),
            ],
        ),
    ]
