# Generated by Django 4.1.7 on 2023-03-04 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('secretary', 'Secretary'), ('associate director', 'Associate Director'), ('director', 'Director')], max_length=150),
        ),
    ]
