# Generated by Django 4.1.7 on 2023-03-04 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_employee_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('director', 'Director'), ('secretary', 'Secretary'), ('associate director', 'Associate Director')], max_length=150),
        ),
    ]
