# Generated by Django 4.1.7 on 2023-03-06 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_employee_user_alter_employee_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('secretary', 'Secretary'), ('associate director', 'Associate Director'), ('director', 'Director')], max_length=150),
        ),
    ]
