# Generated by Django 4.1.7 on 2023-03-07 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_employee_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('director', 'Director'), ('associate director', 'Associate Director'), ('secretary', 'Secretary')], max_length=150),
        ),
    ]
